services:
  rifles:
    image: ghcr.io/dodgerbluee/rifles-only:latest
    container_name: rifles
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
